### ISSUE TITLE
MerryError

### ISSUE THREAD

**Issue by hongzhangMu** [bojone/simple-chinese-ocr#1]
hi:
when I run model_training.py .this has some error.can you help me?
Traceback (most recent call last):
  File "model_training.py", line 57, in <module>
    y = np_utils.to_categorical(range(3062)*45*5*2, nb_classes)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/np_utils.py", line 27, in to_categorical
    categorical = np.zeros((n, nb_classes))
MemoryError

**Comment by bojone** [comment]
you need to try model.fit_generator(), see: http://keras-cn.readthedocs.io/en/latest/models/sequential/
